service:
  name: udagram-ecommerce-app-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  topicName: ecommerceTopic-${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    SIGNED_URL_EXPIRATION: 600
    BRANDS_TABLE: Brands-${self:provider.stage}
    BRAND_ADMINS_TABLE: Brand-Admins-${self:provider.stage}
    ITEMS_TABLE: Items-${self:provider.stage}
    ITEM_IMAGES_TABLE: ItemImages-${self:provider.stage}
    MEMBERS_TABLE: Members-${self:provider.stage}
    INVOICES_TABLE: Invoices-${self:provider.stage}
    OAUTH_TABLE: Oauth-${self:provider.stage}
    ITEM_ID_INDEX: itemIdIndex
    MEMBER_ID_INDEX: memberIdIndex
    BRAND_ID_INDEX: brandIdIndex
    BRAND_ID_SORTED_INDEX: brandIdSortedIndex
    BRAND_ADMIN_ID_INDEX: brandAdminIdIndex
    BRAND_ADMIN_BRAND_ID_INDEX: brandAdminBrandIdIndex
    OAUTH_ID_INDEX: oauthIdIndex
    INVOICE_ID_INDEX: IndexIdIndex
    INVOICE_STAGE_INDEX: InvoiceStageIndex
    INVOICE_ID_SORTED_INDEX: IndexIdSortedIndex
    MEMBER_ID_SORTED_INDEX: memberIdSortedIndex
    IMAGES_S3_BUCKET: serverless-udagram-ecommerce-images-andrcha3-${self:provider.stage}
    THUMBNAILS_S3_BUCKET: serverless-udagram-ecommerce-thumbnail-andrcha3-${self:provider.stage}

    
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  postBrand:
    handler: src/lambda/http/brand/postBrand.handler 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BRANDS_TABLE} 
    events:
      - http:
          method: post
          path: brand
          cors: true

  getBrand:
    handler: src/lambda/http/brand/getBrand.handler 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BRANDS_TABLE} 
    events:
      - http:
          method: get
          path: brand/{brandId}
          cors: true

  getAllBrands:
    handler: src/lambda/http/brand/getAllBrands.handler 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BRANDS_TABLE} 
    events:
      - http:
          method: get
          path: allBrands
          cors: true

resources:
  Resources:
    BrandsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.BRANDS_TABLE}
        AttributeDefinitions:
          - AttributeName: brandId
            AttributeType: S
          - AttributeName: brandAdminId
            AttributeType: S
        KeySchema:
          - AttributeName: brandId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.BRAND_ADMIN_ID_INDEX}
            KeySchema:
              - AttributeName: brandAdminId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    BrandAdminsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.BRAND_ADMINS_TABLE}
        AttributeDefinitions:
          - AttributeName: adminId
            AttributeType: S
          - AttributeName: brandId
            AttributeType: S
          - AttributeName: adminHash
            AttributeType: S
        KeySchema:
          - AttributeName: adminHash
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.BRAND_ADMIN_BRAND_ID_INDEX}
            KeySchema:
              - AttributeName: brandId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.BRAND_ADMIN_ID_INDEX}
            KeySchema:
              - AttributeName: adminId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
              
    MembersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MEMBERS_TABLE}
        AttributeDefinitions:
          - AttributeName: memberId
            AttributeType: S
          - AttributeName: oauthId
            AttributeType: S
        KeySchema:
          - AttributeName: memberId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.OAUTH_ID_INDEX}
            KeySchema:
              - AttributeName: oauthId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    OAuthDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.OAUTH_TABLE}
        AttributeDefinitions:
          - AttributeName: memberId
            AttributeType: S
          - AttributeName: oauthId
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.OAUTH_ID_INDEX}
            KeySchema:
              - AttributeName: oauthId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.MEMBER_ID_INDEX}
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ItemImagesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.ITEM_IMAGES_TABLE}
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: imageId
            AttributeType: S
          - AttributeName: createDatetime
            AttributeType: S
        KeySchema:
          - AttributeName: imageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.ITEM_ID_INDEX}
            KeySchema:
              - AttributeName: itemId
                KeyType: HASH
              - AttributeName: createDatetime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    ItemsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.ITEMS_TABLE}
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: brandId
            AttributeType: S
          - AttributeName: latestUpdateDatetime
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.BRAND_ID_INDEX}
            KeySchema:
              - AttributeName: brandId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.BRAND_ID_SORTED_INDEX}
            KeySchema:
              - AttributeName: brandId
                KeyType: HASH
              - AttributeName: latestUpdateDatetime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    InvoicesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.INVOICES_TABLE}
        AttributeDefinitions:
          - AttributeName: invoiceId
            AttributeType: S
          - AttributeName: memberId
            AttributeType: S
          - AttributeName: invoiceStage
            AttributeType: S
          - AttributeName: latestAddedDatetime
            AttributeType: S
        KeySchema:
          - AttributeName: invoiceId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INVOICE_STAGE_INDEX}
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: invoiceStage
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.INVOICE_ID_SORTED_INDEX}
            KeySchema:
              - AttributeName: invoiceId
                KeyType: HASH
              - AttributeName: latestAddedDatetime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.MEMBER_ID_INDEX}
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.MEMBER_ID_SORTED_INDEX}
            KeySchema:
              - AttributeName: memberId
                KeyType: HASH
              - AttributeName: latestAddedDatetime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL